services:
  postgres:
    image: postgres:latest
    container_name: postgres-go-hrms
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hrms-golang
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: